### ISSUE TITLE
Не могу запустить на Ubuntu 20.04

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#150]
```
Traceback (most recent call last):
  File "main.pyw", line 1318, in <module>
    frame = MainWindow(None, Strings.APP_NAME)
  File "main.pyw", line 347, in __init__
    self.grid.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
AttributeError: type object 'Grid' has no attribute 'wxGridSelectRows'
```

python 3.8.5
wxPython 4.1.0

**Comment by Himura2la** [comment]
Fixed
