### ISSUE TITLE
Ошибка при открытии окна проектора

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#169]
программа открывается но вместо окна проектора выскакивает окно с ошибкой:

```
Traceback (most recent call last):
  File "FestEngine/src/main.pyw", line 569, in ensure_proj_win
    self.proj_win = ProjectorWindow(self, self.config[Config.PROJECTOR_SCREEN])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "FestEngine/src/projector.py", line 140, in __init__
    self.countdown_panel = CountdownPanel(self)
                           ^^^^^^^^^^^^^^^^^^^^
  File "FestEngine/src/projector.py", line 92, in __init__
    self._recalculate_font_size()
  File "FestEngine/src/projector.py", line 101, in _recalculate_font_size
    font.SetPixelSize(wx.Size(0, font_height))
                      ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Size(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 2 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'int'
```

Arch Linux, python-wxpython 4.2.1, python-vlc 3.0.20123, Python 3.11.8

**Comment by Oreolek** [comment]
Попробовал через virtualenv, не помогает но вдруг пригодится скрипт:

```
cd src
virtualenv venv
source ./venv/bin/activate
pip3 install pyinstaller
pip3 install python-vlc
pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-10 wxPython
python3 main.pyw
```

Бинарники из Docker собираются на debian 10 (2019), так что они в принципе не запускаются на свежем Linux, там надо весь старый gtk за собой тащить.

**Comment by Himura2la** [comment]
мне кажется, это пофикшено, там в wx поменялось API
