### ISSUE TITLE
Авторесайз поля notes до заполениня

### ISSUE THREAD

**Issue by Himura2la** [Himura2la/FestEngine#81]

**Comment by Himura2la** [comment]
Баг 

```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/wx/core.py", line 3190, in <lambda>
lambda event: event.callable(*event.args, **event.kw) )
File "src/main.pyw", line 405, in init
grid_autosize_notes_col()
File "src/main.pyw", line 348, in grid_autosize_notes_col
notes_col = self.grid_cols.index(Columns.NOTES)
AttributeError: 'NoneType' object has no attribute 'index'
```
